### ISSUE TITLE
crawler.py throws TypeError 'bool' object is not iterable 

### ISSUE THREAD

**Issue by Gitworm** [Hadesy2k/sqliv#42]
Hey, I tried to use your crawler to check my webserver which has several domains on it against sqli.
Sadly, after checking some of the websites, it throws an error in line 20 of the Crawler.py 

Traceback (most recent call last) :
    File "sqliv.py", line 159, in <module> 
         vulnerables = singleScan (args.target)
    File "sqliv", line 52, in singleScan 
       urls = crawler.crawl(url) 
    File "/home/xxx/Desktop/sqliv/src/crawler.py", line 20, in crawl 
result, URL = html.getHTML(url, True) 
TypeError:   'bool' object is not iterable.

As this was for a -r option scan I tried to do the same for the same single domain and again it throws the same error in line 20 of Crawler.py
Sadly working with Google and stackoverflow I couldn't solve the problem.
Guess I found a site with vulnerability there but
still the error stops me of scanning the other websites.

Operating system is Parrot OS v 3.7
Python Version is 2.7.13

**Comment by Gitworm** [comment]
After some deeper analysis of the case I found out that the website which leads to the error seems to be unreachable. So this could be the reason the error gets thrown. Maybe you could find a way that the script automatically skips unreachable domains ?
