### ISSUE TITLE
ImportError: No module named nyawc.Options

### ISSUE THREAD

**Issue by GoodBlokeAri** [Hadesy2k/sqliv#64]
Installed from git using git clone and install method listed.
```
root@kali:~/Tools# git clone https://github.com/Hadesy2k/sqliv.git && cd sqliv && sudo python2 setup.py -i
Cloning into 'sqliv'...
remote: Counting objects: 825, done.
remote: Total 825 (delta 0), reused 0 (delta 0), pack-reused 825
Receiving objects: 100% (825/825), 893.87 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (462/462), done.
Collecting bs4
  Downloading bs4-0.0.1.tar.gz
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4)
Building wheels for collected packages: bs4
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /root/.cache/pip/wheels/84/67/d4/9e09d9d5adede2ee1c7b7e8775ba3fbb04d07c4f946f0e4f11
Successfully built bs4
Installing collected packages: bs4
Successfully installed bs4-0.0.1
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz
Building wheels for collected packages: termcolor
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /root/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
Successfully built termcolor
Installing collected packages: termcolor
Successfully installed termcolor-1.1.0
Collecting terminaltables
  Downloading terminaltables-3.1.0.tar.gz
Building wheels for collected packages: terminaltables
  Running setup.py bdist_wheel for terminaltables ... done
  Stored in directory: /root/.cache/pip/wheels/96/0c/9a/0ec2bcad2ac1fb1d0e4695879386460cec1a947cd7413d1b17
Successfully built terminaltables
Installing collected packages: terminaltables
Successfully installed terminaltables-3.1.0
Collecting nyawc
  Downloading nyawc-1.8.0.tar.gz
Requirement already satisfied: beautifulsoup4==4.6.0 in /usr/lib/python2.7/dist-packages (from nyawc)
Collecting lxml==4.0.0 (from nyawc)
  Downloading lxml-4.0.0-cp27-cp27mu-manylinux1_x86_64.whl (5.3MB)
    100% |████████████████████████████████| 5.3MB 204kB/s 
Requirement already satisfied: requests==2.18.4 in /usr/lib/python2.7/dist-packages (from nyawc)
Collecting requests_toolbelt==0.8.0 (from nyawc)
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 797kB/s 
Collecting sphinx-better-theme==0.13 (from nyawc)
  Could not find a version that satisfies the requirement sphinx-better-theme==0.13 (from nyawc) (from versions: 0.1, 0.1.4, 0.1.5)
No matching distribution found for sphinx-better-theme==0.13 (from nyawc)
Installation finished
Files are installed under /usr/share/sqliv
Run: sqliv --help
root@kali:~/Tools/sqliv# ls
Dockerfile            lib      README.md         screenshots  sqliv.py
Dockerfile_README.md  LICENSE  requirements.txt  setup.py     src

root@kali:~/Tools/sqliv# python sqliv.py
Traceback (most recent call last):
  File "sqliv.py", line 13, in <module>
    from src.crawler import Crawler
  File "/root/Tools/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named nyawc.Options

```

**Comment by Aalscholver** [comment]
Same problem here, cant get the requirements installed on my kali machine.

**Comment by GoodBlokeAri** [comment]
* this works on 2016.3 kali but not 2018.1?

**Comment by fk6989** [comment]
Same peoblem here.I had not this problem.I removed my kali machine and installed the same iso again(kali linux 2018).but this time I have this error and sqliv doesn’t work.I tried installing kali several times but still same problem exist.please help 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fk6989** [comment]
@GoodBlokeAri  @Aalscholver I found the solution.if you still have the problem tell me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GoodBlokeAri** [comment]
@fk6989 Yes. Let me know

**Comment by fk6989** [comment]
@GoodBlokeAri  what I say is tested on kali linux 2018.first go to this path and show the folders by `ls` command
Path:  `/user/local/lib/python2.7/dist-packages`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fk6989** [comment]
By the way it’s 5:20am here and if I didn’t answer wait until I wake up😂I’m planning to sleep 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GoodBlokeAri** [comment]
@fk6989 Just tell me how you fixed it please 😄

**Comment by fk6989** [comment]
@GoodBlokeAri the problem is that “nyawc” is not installed and won’t be.because of “sphinx-better-theme.013”.so I recieves installed folder of ‘nyawc’ and copied to the python path.can you get a nyawc installed folder?from a friend?if not give me your email address so I can send you this file.after that you run this command :`pip install --upgrade nyawc`.then run `python sqliv.py`.maybe you get this error : `ImportError: No module named requests_toolbelt`.if you got that run `pip install request_toolbet` then run sqliv again.and the problem is over.but firat of all you should install sqliv.then do what I said

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MazenElzanaty** [comment]
Here's a fix tried on Kali 2018.1
Download and sphinx-better-theme 0.1.5
https://pypi.python.org/pypi/sphinx-better-theme
Install it 
python setup.py install

Then Download nyawc 1.8.0
https://pypi.python.org/pypi/nyawc/
After downloading we need to edit the requirements file
Change sphinx-better-theme==0.13
to sphinx-better-theme==0.1.5
There's no version 0.13, version 0.1.5 is the only released one
Then install nyawc
python setup.py install 
It works

**Comment by therzv** [comment]
i solved this issue by just install this 
pip install sphinx-better-theme
pip install nyawc

and it works
