### ISSUE TITLE
 File "sqliv.py", line 13, in <module>     from src.crawler import Crawler ETC.

### ISSUE THREAD

**Issue by frequencyg** [Hadesy2k/sqliv#65]
`root@kali:~/sqliv# python sqliv.py -d "inurl:index.php?id=" -e google  
Traceback (most recent call last):
  File "sqliv.py", line 13, in <module>
    from src.crawler import Crawler
  File "/root/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named nyawc.Options
`

I am using the latest kali linux rolling edition.Any tips?

**Comment by drdos-paradox** [comment]
Yeah. I second that. Running Android 7.1 using Gnuroot Debian.
root@localhost:/sqliv# sqliv --help
Traceback (most recent call last):
  File "/usr/share/sqliv/sqliv.py", line 13, in <module>
    from src.crawler import Crawler
  File "/usr/share/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named nyawc.Options

**Comment by Boris519** [comment]
Same
`root@debian:~/sqliv# python sqliv.py
Traceback (most recent call last):
  File "sqliv.py", line 13, in <module>
    from src.crawler import Crawler
  File "/root/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named `nyawc.Options`

**Comment by DeWolfRobin** [comment]
same windows and linux

**Comment by the-c0d3r** [comment]
`pip install -r requirements.txt`
