### ISSUE TITLE
module problem

### ISSUE THREAD

**Issue by kreptoON** [Hadesy2k/sqliv#68]
oot@xxxx:~/Desktop/sqliv# python sqliv.py -d "inurl:index.php?id=" -e google
Traceback (most recent call last):
  File "sqliv.py", line 13, in <module>
    from src.crawler import crawler
  File "/root/Desktop/sqliv/src/crawler.py", line 5, in <module>
    from nyawc.Options import Options
ImportError: No module named nyawc.Options

**Comment by the-c0d3r** [comment]
`pip install -r requirements.txt`
